name: nginx-server
services:
  nginx:
    image: nginx
    volumes:
      - ${LC_COMMON_ROOT}/nginx:/etc/nginx/conf.d
      - ${LC_COMMON_ROOT}/certs/public/cg_docs.pem:/etc/ssl/certs/cg_docs.pem
      - ${LC_COMMON_ROOT}/certs/private/cg_docs.key:/etc/ssl/private/cg_docs.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      vcg:

networks:
  vcg:
    external: true
    name: vcg