name: wiki
services:
  docmost:
    image: artifactory.lesta.io:443/vcg-docker/docmost:latest
    depends_on:
      - redis
    environment:
      APP_URL: "https://cgdocs.lesta.group"
      PORT: 3000
      APP_SECRET: ${DOCMOST_SECRET}
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD}@${DB_HOST}:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
      MAIL_DRIVER: "smtp"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: "job-vcg_smtp@lesta.group"
      MAIL_FROM_NAME: "Docmost"
      FILE_UPLOAD_SIZE_LIMIT: "200mb"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./docmost:/app/data/storage
    networks:
      - vcg
      - wiki

  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - wiki
volumes:
  docmost:
  redis_data:

networks:
  wiki:
  vcg:
    external: true
    name: vcg