name: wiki
services:
  docmost:
    image: artifactory.lesta.io:443/vcg-docker/docmost:latest
    build:
      context: .
      target: installer
    depends_on:
      - redis
      - db
    restart: always
    env_file:
      - docmost.env
    networks:
      - wiki
      - vcg
    volumes:
      - ${PROJECT_ROOT}/storage:/app/data/storage

  db:
    image: postgres:17-trixie
    volumes:
      - ${PROJECT_ROOT}/postgres_data:/var/lib/postgresql/data

    env_file:
      - db.env
    networks:
      - wiki
    ports:
      - "5434:5432"

  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - ${PROJECT_ROOT}/redis_data:/data
    networks:
      - wiki

volumes:
  docmost:
  redis_data:

networks:
  wiki:
  vcg:
    external: true
    name: vcg